import type { User, Video } from "@/lib/types";

export const dummyUsers: User[] = [
  {
    id: "user1",
    username: "fitfreak",
    password: "password123",
    profilePicture: "https://picsum.photos/seed/profile1/200/200",
    bio: "Just a gym enthusiast sharing my journey. #fitness #gymlife",
    followers: [],
    following: [],
  },
  {
    id: "user2",
    username: "yogaguru",
    password: "password123",
    profilePicture: "https://picsum.photos/seed/profile2/200/200",
    bio: "Finding balance one pose at a time.",
    followers: [],
    following: [],
  },
  {
    id: "user3",
    username: "runwild",
    password: "password123",
    profilePicture: "https://picsum.photos/seed/profile3/200/200",
    bio: "Exploring the world on two feet.",
    followers: [],
    following: [],
  },
  {
    id: "user4",
    username: "crossfitchamp",
    password: "password123",
    profilePicture: "https://picsum.photos/seed/profile4/200/200",
    bio: "Beast mode on. Pushing my limits daily.",
    followers: [],
    following: [],
  },
  {
    id: "user5",
    username: "healthyeats",
    password: "password123",
    profilePicture: "https://picsum.photos/seed/profile5/200/200",
    bio: "Fueling my body with the best.",
    followers: [],
    following: [],
  },
  {
    id: "user6",
    username: "flexdiana",
    password: "password123",
    profilePicture: "https://picsum.photos/seed/profile6/200/200",
    bio: "Stretching towards my goals.",
    followers: [],
    following: [],
  },
];

export const dummyVideos: Video[] = [
  {
    id: "video1",
    userId: "user1",
    videoUrl: "/videos/video1.mp4",
    posterUrl: "https://picsum.photos/seed/poster1/540/960",
    caption: "Workout motivation to kick off the day.",
    likes: [],
    comments: [],
    shares: 10,
    isUploaded: false,
  },
  {
    id: "video2",
    userId: "user2",
    videoUrl: "/videos/video2.mp4",
    posterUrl: "https://picsum.photos/seed/poster2/540/960",
    caption: "Morning yoga flow and a little reset.",
    likes: [],
    comments: [],
    shares: 5,
    isUploaded: false,
  },
  {
    id: "video3",
    userId: "user3",
    videoUrl: "/videos/video3.mp4",
    posterUrl: "https://picsum.photos/seed/poster3/540/960",
    caption: "Running through nature never gets old.",
    likes: [],
    comments: [],
    shares: 8,
    isUploaded: false,
  },
  {
    id: "video4",
    userId: "user4",
    videoUrl: "/videos/video4.mp4",
    posterUrl: "https://picsum.photos/seed/poster4/540/960",
    caption: "Short CrossFit burst with full focus.",
    likes: [],
    comments: [],
    shares: 6,
    isUploaded: false,
  },
  {
    id: "video5",
    userId: "user5",
    videoUrl: "/videos/video5.mp4",
    posterUrl: "https://picsum.photos/seed/poster5/540/960",
    caption: "Another solid session in the books.",
    likes: [],
    comments: [],
    shares: 4,
    isUploaded: false,
  },
];
